# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
android.enableJetifier=true
kotlin.code.style=official
org.gradle.daemon=false
org.gradle.parallel=true
# Allow AGP 8.4.0 to compile against Android 16 (API 36).
android.suppressUnsupportedCompileSdk=36